const { colors } = require("tailwindcss/defaultTheme");

module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        background: "#f0f2f5",
        foreground: "#1e2a3a",
        card: "#ffffff",
        primary: "#0f7a4f",
        "primary-foreground": "#FFFFFF",
        secondary: "#edf5ee",
        "secondary-foreground": "#1f3d2a",
        muted: "#f0f1f3",
        "muted-foreground": "#6b7280",
        accent: "#14b8a6",
        "accent-foreground": "#ffffff",
        destructive: "#ef4444",
        "destructive-foreground": "#ffffff",
        info: "#3b82f6",
        warning: "#f59e0b",
        success: "#22c55e",
        border: "#e5e7eb",
        input: "#e5e7eb",
        ring: "#0f7a4f",
        login_panel: "#13352B",
        wheat: "#eab308",
        "wheat-foreground": "#1e2a3a",
        sidebar: "#0f3d2a",
        "sidebar-foreground": "#c2d4c8",
        "sidebar-primary": "#14b8a6",
        "sidebar-accent": "#1a5c3a",
        "sidebar-accent-foreground": "#e8f0ea",
        "sidebar-border": "#1f5c3d",
        "sidebar-ring": "#14b8a6",
        "sidebar-muted": "#7a9a85",
        "button-primary": "#055B1D",
      },
      fontFamily: {
        inter: ["InterRegular"],
        interBold: ["InterBold"],
        interMedium: ["InterMedium"],
        interBlack: ["InterBlack"],
      },
    },
  },
  plugins: [],
};